### ISSUE TITLE
[question] DIfference from pass

### ISSUE THREAD

**Issue by krautcat** [dylanaraps/pash#1]
I can't guess the purpose of this manager when [https://github.com/zx2c4/password-store](pass) exists. What's the goal of this project?

I'm just asking the question to elaborate for myself possible usecases of this password manager.

**Comment by dylanaraps** [comment]
The source for `pass` is rather complex and relies on things like `eval` which I don't really like. The source is rather messy and isn't anywhere near shellcheck compliance. `pash` is tiny, simple, shellcheck compliant and pure bash (*other than calls to `gpg`, `xclip` and `mkdir`*).

That being said, `password-store` is a mature program and `pash` is a newborn in comparison. If you care about your password manager being written in a "safe" way then you'll see the value in `pash`.

I'll also be working on this actively and I'm open to adding features. :)

**Comment by krautcat** [comment]
Compliance to shellcheck is something I required from myself when I write shell scripts. This is important feature for code quality IMO.

So, as far as I can understand, the main goal of this project is to create drop-in replacement for `password-store` with better code quality and less bloated in comparison with it.

Thank you for quick response!

**Comment by dylanaraps** [comment]
I can't guarantee full `password-store` compatibility (*it doesn't currently support it at all*) but this can and may be added in the near future.
