### ISSUE TITLE
Improved heredoc syntax

### ISSUE THREAD

**Issue by ghost** [dylanaraps/pash#13]
This syntax:

https://github.com/dylanaraps/pash/blob/79b55134402b515d4735be4561c7408b193b48fd/pash#L50-L53

I would say is highly confusing. Here is a simple example replicating the
syntax:

~~~sh
grep -q day <<eof && \
echo pass
sunday monday
eof
~~~

This would be better written like this:

~~~sh
grep -q day <<eof && echo pass
sunday monday
eof
~~~

or better yet:

~~~sh
grep -q day <<eof &&
sunday monday
eof
echo pass
~~~

**Comment by dylanaraps** [comment]
Thanks for opening the issue. :+1:
