### ISSUE TITLE
Add autocomplete for passwords in directories

### ISSUE THREAD

**Issue by Tulkdan** [dylanaraps/pash#16]
Hi,
I love the simplicity in comparison to `pass`, but one thing that I'm missing is the autocomplete when searching for a password that is stored in a directory, it would be a great feature to implement :)

**Comment by dylanaraps** [comment]
Thanks :)

This is more of a "contrib" thing for distribution right? ie, completion files for bash, zsh, fish, whatever.

**Comment by Tulkdan** [comment]
Yes, I'm totally noob with CLIs and don't know the complexity to implement it. Also, if it doesn't make sense for the project you can close this suggestion.

**Comment by NikosAlexandris** [comment]
This has been closed because it has been implemented? If yes, how should it work?
