### ISSUE TITLE
pash is unusable

### ISSUE THREAD

**Issue by 400thecat** [dylanaraps/pash#18]
Sorry, but pash is unusable. The user interface is confusing and anti-intuitive.

For instance, I want to create a new entry:

  pash a test
  Generate a password? [y/n]:

WTF ? what password ?
I don't understand. I want to use my public gpg key to encrypt new entry. What password is pash asking for ?

Next step:

Generate a password? [y/n]: n
Enter password: 
Enter password (again): 

and then it launches gpg agent and asks yet for another password. But what password ?

Really confusing.

I really wanted to like pash, but I don't understand how it is supposed to work. I used pass before, and had no issues.

**Comment by 400thecat** [comment]
To clarify:

I would expect following behavior when adding new entry:

1. pash a test
2. default editor opens, and I can add my details into text file
3. upon exit, the text file is encrypted with default gpg key (unless other key specified)
4. pash l test - should simply list contents of encrypted file (after password was provided)

this is how pass works, and this is how it makes sense

**Comment by 400thecat** [comment]
also, there is no way to edit an existing entry

**Comment by dylanaraps** [comment]
Current behavior is what will stay. I don't see any issues with it.
