### ISSUE TITLE
Duplicate effort?

### ISSUE THREAD

**Issue by dvn0** [dylanaraps/pash#2]
This seems an awful lot like: https://www.passwordstore.org/

> Password management should be simple and follow Unix philosophy. With pass, each password lives inside of a gpg encrypted file whose filename is the title of the website or resource that requires the password. These encrypted files may be organized into meaningful folder hierarchies, copied from computer to computer, and, in general, manipulated using standard command line file management utilities.

Are there [planned] fundamental differences?

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/pash/issues/1

**Comment by dvn0** [comment]
Ah, I should have looked at closed issues! I appreciate your responses in that issue. Thanks!
