### ISSUE TITLE
pash show also when using absolute filenames

### ISSUE THREAD

**Issue by NikosAlexandris** [dylanaraps/pash#22]
This errors out:
```
pash show /data/cloud/passwords/.pashword-store/internet/someurl.gpg
```
```
error: Pass file '/data/cloud/passwords/.pashword-store/internet/someurl.gpg' doesn't exist.
```

This could be an alternative way to use bash' filename auto-completion.

**Comment by aabacchus** [comment]
If you're going to bypass the abstraction provided by pash, you should just do `gpg -d /path/to/file.gpg`.

**Comment by NikosAlexandris** [comment]
> If you're going to bypass the abstraction provided by pash, you should just do `gpg -d /path/to/file.gpg`.

I had a look in the source code, and figured this out. I wonder, however, how hard it is to make auto-completion work seamlessly, no matter where the "pash store" is located.

**Comment by aabacchus** [comment]
If it's something you'd like, then great. Auto-completion is shell-specific and very much not POSIX sh, so is outside the scope of being inside pash itself.

**Comment by NikosAlexandris** [comment]
> If it's something you'd like, then great. Auto-completion is shell-specific and very much not POSIX sh, so is outside the scope of being inside pash itself.

I take this as an "out-of-scope" answer then and close this issue. Thank you.
