### ISSUE TITLE
[usage] What's the popup for?

### ISSUE THREAD

**Issue by kiedtl** [dylanaraps/pash#3]
Just tried out pash, like it a lot :)

Was just wondering why the GPG 'enter your passcode' thing is there for. Is that where I enter my master password or the website password?

**Comment by dylanaraps** [comment]
The `gpg` password dialog is for setting the password to encrypt the file with. I haven't added support for using a public/private key as I have no use for it (I'd accept PRs to add it however.). I just set the same master password for each entry I create and it mimics my prior `keepassxc` usage.

**Comment by kiedtl** [comment]
Thanks!
