### ISSUE TITLE
gpg: error with agent

### ISSUE THREAD

**Issue by kiedtl** [dylanaraps/pash#4]
I get this error when trying to create a new password entry:
```
➜ pash a dev/stackoverflow
Generate a password? [y/n]: y
gpg: problem with the agent: Not a tty
gpg: error creating passphrase: Operation cancelled
gpg: symmetric encryption of '[stdin]' failed: Operation cancelled
```
Environment info:
- distro: alpine linux

Everything seems to be working on my Arch installation however.

**Comment by dylanaraps** [comment]
You may need to add this to your `.bashrc` (or equivalent).

```sh
export GPG_TTY=$(tty)
```

**Comment by dylanaraps** [comment]
Fixed in master.
