### ISSUE TITLE
GPG: Invalid IPC response

### ISSUE THREAD

**Issue by drozdowsky** [dylanaraps/pash#7]
Thanks for rewritting in sh, I have tried to run it on FreeBSD but I got this:
```
Invalid IPC response
```
 on this line
```sh
  echo "$pass" | GPG_TTY=$(tty) "$gpg" "$@" -o "$name.gpg" &&
        printf '%s\n' "Saved '$name' to the store."
```
I can send full 'traceback' tomorrow as of now I am not on the same machine.

**Comment by dylanaraps** [comment]
I've pushed a potential fix. :+1:

**Comment by drozdowsky** [comment]
fixed
but when I try to copy the entry I get this:
```sh
$ ./pash c test2
/home/self/test: No such file or directory
```
where 'test' is password to test2.
Should I open another ticket?

**Comment by dylanaraps** [comment]
Interesting, the code for this is really simple:

```sh
pw_show() {
    pass=$("$gpg" -dq "$1.gpg")

    # If '$2' is defined, don't print the password to the
    # terminal. For example, this is used when the password is
    # copied to the clipboard.
    [ "$2" ] || printf '%s\n' "$pass"
}

pw_copy() {
    pw_show "$1" copy

    if [ "$TMUX" ]; then
        tmux load-buffer "$pass"

    elif hash xclip; then
        echo "$pass" | xclip -selection clipboard
    fi
}
```

Is the issue in the `gpg` command perhaps?

**Comment by drozdowsky** [comment]
gpg returns test and its ok.

No such file is related to tmux.
```
$ tmux load-buffer "test"
/home/self/test: No such file or directory
```

**Comment by dylanaraps** [comment]
Nice, what would the correct syntax be to copy to `tmux`'s clipboard?

**Comment by drozdowsky** [comment]
tbh I do not know if tmux has his own clipboard.
My tmux copy on selection works like this:
```
bind-key -Tcopy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "cpb"
```
and cpb is basically xclip with timeout:
```sh
[ -n "$1" ] && exec 3<"$1" || exec 3<&0
cat <&3 | timeout 120 xclip -r -i -sel c -verbose >/dev/null 2>&1 &
```
I think I would like to copy it to system clipboard right away with xclip/etc.
What do you think of custom variable that specifies command to copy the password? e.g.
```sh
echo "$pass" | ${PASH_CLIP:-xclip}
```

**Comment by dylanaraps** [comment]
Done. :)

**Comment by dylanaraps** [comment]
Thoughts on this change?: https://github.com/dylanaraps/pash/pull/10

It was requested on Reddit that this be implemented in `pash` itself to make it "secure".

**Comment by drozdowsky** [comment]
I am okay with this but how do you make sure that user hasnt copied anything else and therefore do not clean his clipboard.
Thats why I used `timeout` in my cpb. 
Note that `timeout` is GNUism (BSD does not have timeout), I wonder if you can make secure version of timeout in sh (I could not).

**Comment by dylanaraps** [comment]
> I am okay with this but how do you make sure that user hasnt copied anything else and therefore do not clean his clipboard.

I'm not sure that I understand. This will clear the clipboard regardless of whether or not the user has copied something else, no? Edit: Yup it does.

**Comment by drozdowsky** [comment]
Yes, you should kill the PID, xclip exits when user copies something else so make sure that PID is the same instance of xclip (thats why timeout is nice)

**Comment by dylanaraps** [comment]
My solution will still clear the clipboard even when `xclip` isn't running as it executes a second `xclip` to clear the clipboard. Please confirm. :)

**Comment by drozdowsky** [comment]
xclip runs forever until you copy something else, basically in x11 almost every application has his own clipboard, thats why when you copy something e.g. in firefox and exit, you lose clipboard. so xclip runs forever until you kill it (and then you lose/clear clipboard).
 
Dont know about `xclip </dev/null`
but `echo "" | xclip` can run forever  

so yes, if user copied something else you clear it rn 

thats why I have written cpb, I do not like running xclip forever

**Comment by dylanaraps** [comment]
> so yes, if user copied something else you clear it rn

Does this meet your criteria for secure?  Is this solution OK for your needs? I want to get feedback before I push anything to master. :)

**Comment by drozdowsky** [comment]
I would say for me this is a bug, it is secure but it is not user friendly, what happens when I copy second password? :) if I understand current implementation correctly, first copy will kill second copy  (if timeout is high enough) 


test: `PASH_CLIP="timeout 10 | xclip ..." ` for proper implementation

**Comment by dylanaraps** [comment]
You're right but this solution also works for all clipboard tools and not just `xclip`. That's the upside. Will keep digging.

**Comment by drozdowsky** [comment]
what do you mean by all clipboard tools? you mean clearing clipboard of other tools? I do not see use case for this, what do you think

**Comment by dylanaraps** [comment]
If you set `PASH_CLIP` to use `wl-copy` (Wayland) or `xsel` it'll still clear the password after the timer.

**Comment by drozdowsky** [comment]
Ohhh, ok. I do not know how wl-copy works, but xsel probably works similar to xclip, killing it clears the clipboard (but xsel has not option to not go into daemon mode if I remember correctly so using timeout is out of question)

Note that xclip has -l
and xsel has -t
Do not know if it is better to handle this in pash or specify it with PASH_CLIP.

**Comment by dylanaraps** [comment]
`xclip`'s `-l` doesn't work correctly: https://github.com/astrand/xclip/issues/73

`xel`'s `-t` also doesn't work as described. It states `ms` but really uses seconds? Either way it doesn't seem to work well on my machine at all.

I have pushed an update to the PR to allow for `PASH_TIMEOUT=off` which disables the timeout entirely. This will allow you to continue to use your script while allowing for the new timeout feature to still function (if desired). :)
